name: adb_mobile
description: "ADB Mobile project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.1
  flutter_screenutil: ^5.9.3
  rxdart: ^0.28.0
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  video_player: ^2.9.1
  chewie: ^1.8.3
  youtube_player_flutter: ^9.0.2
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  hive: ^2.2.3
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
