name: adb_mobile
description: "ADB Mobile project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.1
  flutter_screenutil: ^5.9.3
  rxdart: ^0.28.0
  cached_network_image: ^3.4.0
  intl: ^0.19.0
  video_player: ^2.8.1
  chewie: ^1.8.1
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  hive: ^2.2.3
  permission_handler: ^10.2.0
  device_info_plus: ^10.1.1
  open_filex: ^4.4.0
  font_awesome_flutter: ^10.7.0
  badges: ^3.1.2
  image_picker: ^1.1.2
  http_parser: ^4.0.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_pdfviewer: ^26.2.9
  wakelock_plus: ^1.1.4
  path_provider: ^2.1.2
  mime: ^1.0.4
  timeago: ^3.6.0
  share_plus: ^7.2.1
  saf: ^1.0.3+4
  animated_custom_dropdown: ^3.1.1
  flutter_pdfview: ^1.3.2
  flutter_widget_from_html: ^0.15.0
  pin_code_fields: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/pdf/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          style: normal
